[package]
name = "lvos-ipc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["io-util", "net"] }
uuid.workspace = true

[lints]
workspace = true
