[package]
name = "lvos-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
lvos-core = { path = "../core" }
lvos-sync = { path = "../sync" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile = "3.27.0"
uuid.workspace = true

[lints]
workspace = true
