[package]
name = "lvos-translation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
lvos-auth = { path = "../auth" }
lvos-core = { path = "../core" }
reqwest.workspace = true
rustls.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
