[package]
name = "lvos-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
sha2.workspace = true
unicode-casefold.workspace = true
unicode-normalization.workspace = true
unicode-script.workspace = true

[lints]
workspace = true
